!  Fortran Console Application 
!  Generated by PGI Visual Fortran(R)
!  5/9/2014 2:42:39 PM
!  Compiled by XUYUAN LI
!  The University of Adelaide
!  Open sources code (application version) for the following journal paper:
!  ********************************************************************
!  Li X., Zecchin A.C. and Maier H.R. 2014, 'Selection of smoothing parameter estimators 
!  for General Regression Neural Networks - applications to hydrological and water resources modelling', 
!  Environmental Modelling and Software, accepted May 6, 2014
!  ********************************************************************

      program GRNNS9SP
      
      use GFS         !General functions
      use GRNN_GRR    !with Gaussian reference rule (GRR) (Scott, 1992)
      use GRNN_BCV    !with Biased cross validation (BCV) (Scott and Terrell, 1987)
      use GRNN_DPI    !with 2-stage direct plug-in (DPI) (Park and Marron, 1992)
      use GRNN_BCVDPI !with a combination of BCV and DPI (BCVDPI) (Wand and Jones, 1995)
      use GRNN_SCV    !with Smoothed cross validation (SCV)  (Hall et al., 1992)
      use GRNN_TESOSE !with trial & error (single-variable; Objective function:Sum of squared error)(Gibbs et al., 2006; Press et al., 1992)
      use GRNN_TESOME !with trial & error (single-variable; Objective function:Sum of mean abs. error)(Gibbs et al., 2006; Press et al., 1992)
      use GRNN_TEMOSE !with trial & error (multi-variable; Objective function:Sum of squared error)(Gibbs et al., 2006; Poli et al., 2007)
      use GRNN_TEMOME !with trial & error (multi-variable; Objective function:Sum of mean abs. error)(Gibbs et al., 2006; Poli et al., 2007)
      
      implicit none
            
      !1.Variables
      real(8),allocatable::allinput(:,:),alloutput(:)  !All inputs & output
      real(8),allocatable::inputx(:,:),outputy(:)      !Inputs & output for each test 
      real(8),allocatable::inputxs(:,:),outputys(:)    !standardised data
      real(8),allocatable::t(:,:)                      !recording all computational time
      integer(8)::row,col                              !Row (no. of data), columns (no. of inputs)
      integer(8)::c1,c2,c3,c4,c5,c6,c7,c8,c9,c10       !Counters
      real(8)::t1,t2                                   !Computational time (starting & ending time)
      character(len=22),allocatable::fn(:)             !File 1 (For all detail results)
      character(len=23),allocatable::fns(:)            !File 2 (For all summary results) 
      character(len=19),allocatable::fnh(:)            !File 3 (For all smoothing parameter results) 
      character(len=1)::fn1                            !File # (For all detail results) 
      
      
      integer(8)::a1
      integer(8)::a2                                   !No. of repeatings: e.g 1 (just 1 trial), 30 (30 trials)  
      integer(8)::a3                                   !Method code  
      
      
write(*,'(A77)')"*****************************************************************************"
write(*,'(A77)')"*                      The University of Adelaide                           *"
write(*,'(A77)')"*             School of Civil, Environmental & Mining Engineering           *"
write(*,'(A77)')"*                    Li, X, Zecchin, AC & Maier, HR                         *"
write(*,'(A77)')"*                 Open sources code (application version) 06/05/14          *"
write(*,'(A77)')"*****************************************************************************" 
      
      write(*,*)                           
      a1=1   
      write(*,'(A63)')"Please type in no. of repeating tests (integer; select from 1):"
      read(*,*)a2
      write(*,*)
 
write(*,'(A65)')"Please choose the GRNNs with proper smoothing parameter estimator"
write(*,'(A77)')"*****************************************************************************"
write(*,'(A77)')"*Type 1                    Gaussian reference rule (GRR)                    *"
write(*,'(A77)')"*Type 2                    Biased cross validation (BCV)                    *"        
write(*,'(A77)')"*Type 3                     2-stage direct plug-in (DPI)                    *"
write(*,'(A77)')"*Type 4                 a combination of BCV and DPI (BCVDPI)               *" 
write(*,'(A77)')"*Type 5                   Smoothed cross validation (SCV)                   *"
write(*,'(A77)')"*Type 6     Single variable calibration with squared error O.F. (SVCS)      *"
write(*,'(A77)')"*Type 7   Single variable calibration with mean absolute error O.F. (SVCA)  *"
write(*,'(A77)')"*Type 8      Multivariable calibration with squared error O.F. (MVCS)       *"
write(*,'(A77)')"*Type 9    Multi-variable calibration with mean absolute error O.F. (MVCA)  *"
write(*,'(A77)')"*****************************************************************************" 
read(*,*)a3
write(*,*)  

      !2.Generate output files  
      allocate(fn(a1))    
      allocate(fns(a1))   
      allocate(fnh(a1))   
      allocate(t(a2,a1))  
      
      do c3=1,a1                             
         write(fn1,'(I1)')c3
         fn(c3)="Test_detailoutput"//trim(fn1)//".txt"  !File name for detail results
         fns(c3)="Test_summaryoutput"//trim(fn1)//".txt"  !File name for summary results
         fnh(c3)="Test_bandwidth"//trim(fn1)//".txt"  !File name for summary results
         c4=199+c3    !File code
         c9=299+c3    !File code
         c10=399+c3   !File code
         open (unit=c4,file=fn(c3),status='replace')  !detail results
         open (unit=c9,file=fns(c3),status='replace')  !summary results
         open (unit=c10,file=fnh(c3),status='replace')  !summary results
      end do
      
      !3.Numerical analysis
      !3.1 Load from input file
      !**************************************************************Please change the input file name below;  
      open (unit=111,file="EAR4_NORM.txt",status='old') !************************************Load input file; 
      read(111,*)row,col
      allocate(allinput(row,col))
      allocate(alloutput(row))
      do c1=1,row
         read(111,*)(allinput(c1,c2),c2=1,col),alloutput(c1)
      end do
      c6=row/a2                                            
      allocate(inputx(c6,col)) 
      allocate(outputy(c6)) 
      allocate(inputxs(c6,col)) 
      allocate(outputys(c6)) 
      
      !3.2 Generate output file  
      do c3=1,a1       
         c9=299+c3
         
         select case (a3)
          case (1)
          write(c9,*)"By GRR based GRNNs:"
          case (2)
          write(c9,*)"By BCV based GRNNs:"
          case (3)
          write(c9,*)"By DPI based GRNNs:"
          case (4)
          write(c9,*)"By BCVDPI based GRNNs:"
          case (5)
          write(c9,*)"By SCV based GRNNs:"
          case (6)
          write(c9,*)"By SVCS based GRNNs:"
          case (7)
          write(c9,*)"By SVCA based GRNNs:"
          case (8)
          write(c9,*)"By MVCS based GRNNs:"
          case (9)
          write(c9,*)"By MVCA based GRNNs:"          
          end select 
          
         write(c9,'(14A11)')"min","max","mean","Var","s","k","RMSE","MARE",&
         "CE","IoAd","PI","MCE","MIoAd","MPI" !Criteria
      end do
      
      do c3=1,a1      
         c10=399+c3
         write(c10,'(A20)')"Bandwidth parameter:"
      end do   
           
      !3.3 Tests       
 do c5=1,a2      
 
    do c3=1,a1          
       c4=199+c3
       write(c4,*)
       write(c4,'(A18,I2,A10)')"**********TEST No.",c5,"**********" 
    end do
    
    do c3=1,a1        
        do c2=1,col    
           c7=(c5-1)*row/a2  
           do c1=1,c6
              c8=c7+c1
              inputx(c1,c2)=allinput(c8,c2)
           end do
        end do
        
        c7=(c5-1)*row/a2                 
        do c1=1,c6
           c8=c7+c1
           outputy(c1)=alloutput(c8)
        end do      
        
        !standardised data
        do c2=1,col
           call sd(inputx(1:c6,c2),c6,inputxs(1:c6,c2))
        end do
           call sd(outputy(1:c6),c6,outputys(1:c6))
    
        call CPU_time(t1)
        c4=199+c3
           
       select case (a3)
        case (1)
        call BW_GRR(c4,inputxs,outputys,c6,col)   !Results summary (BW: Gaussian Reference Rule with single SP) 
        case (2)
        call BW_BCV(c4,inputxs,outputys,c6,col) !Results summary (trial & error, single objective, SE)
        case (3)
        call BW_DPI(c4,inputxs,outputys,c6,col) !Results summary (trial & error, single objective, ME)
        case (4)
        call BW_BCVDPI(c4,inputxs,outputys,c6,col)!Results summary (trial & error, multi objective, SE)
        case (5)
        call BW_SCV(c4,inputxs,outputys,c6,col)!Results summary (trial & error, multi objective, ME) 
        case (6)
        call BW_TESSE(c4,inputxs,outputys,c6,col)!Results summary (trial & error, multi objective, ME)
        case (7)
        call BW_TESME(c4,inputxs,outputys,c6,col)!Results summary (trial & error, multi objective, ME)
        case (8)
        call BW_TEMOSE(c4,inputxs,outputys,c6,col)!Results summary (trial & error, multi objective, ME)
        case (9)
        call BW_TEMOME(c4,inputxs,outputys,c6,col)!Results summary (trial & error, multi objective, ME)
       end select            
           
        call CPU_time(t2)
        t(c5,c3)=t2-t1
        write(c4,'(A26,F9.2,A1)')"The computational time is:",t(c5,c3),"s"    
   end do 
   
   write(*,'(I3,X,A6,I3,X,A23)')c5,"out of",a2,"tests is/are completed!"     
   
end do 

     !3.4 Write outputs (CT)
      do c3=1,a1             !changable e.g. 5 different bandwidth algorithms (8)
         c9=299+c3 
         write(c9,'(A4)')"Time" 
         do c5=1,a2          !changable e.g. 30 IV  (6)
            write(c9,'(F9.4)')t(c5,c3)
          end do
      end do 
      
      
      !4.Ending
      close(111)
      do c3=1,a1            
         c4=199+c3
         close(c4)
      end do   
      
      do c3=1,a1            
         c9=299+c3
         close(c9)
      end do 
      
      do c3=1,a1            
         c10=399+c3
         close(c10)
      end do 
      
      write(*,*) 
      write(*,'(A28)')"Please check output summary."
      read(*,*)
      
      deallocate(fn) 
      deallocate(fns) 
      deallocate(fnh)
      deallocate(allinput)
      deallocate(alloutput)
      deallocate(inputxs) 
      deallocate(outputys) 
      deallocate(inputx)
      deallocate(outputy)
      deallocate(t)  
      
      end program GRNNS9SP
